apiVersion: apps/v1
kind: Deployment
metadata:
  name: magic
spec:
  selector:
    matchLabels:
      run: magic
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
      labels:
        run: magic
    spec:
      containers:
        - name: magic
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command: [ "npm" ]
          args: [ "run", "start:player-server" ]
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: NODE_ENV
            - name: GATEWAY_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: GATEWAY_URL
            - name: MODELS_MANAGER_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: MODELS_MANAGER_URL
            - name: MM_MASTER_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  name: {{ .Release.Name }}-configmap
                  key: MM_MASTER_SERVER_URL
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: web2
                  key: jwtSecret
