apiVersion: v1
kind: Service
metadata:
  name: magic
  labels:
    run: magic
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 3001
  selector:
    run: magic
