// taken from
// https://github.com/sr-2020/nodejs-monorepo/blob/c86e7c357c2adc5352fc9a38478f20e971262acb/packages/sr2020-common/models/qr-code.model.ts

export type QrType =
  // Ones named in a CAPS_CASE are only generated by client Android app
  | 'HEALTHY_BODY'
  | 'WOUNDED_BODY'
  | 'CLINICALLY_DEAD_BODY'
  | 'ABSOLUTELY_DEAD_BODY'
  | 'ASTRAL_BODY'
  | 'ECTOPLASM_BODY'
  | 'ROBOT_BODY'
  // Ones in snake_case are rewritable ones stored in the database
  | 'empty' // Empty QR, can be written.
  | 'pill' // Pharmaceuticals and similar
  | 'implant' // Implant bought in the shop or cut from the body.
  | 'food' // Food item
  | 'ability' // Used for mental abilities - ability which affects the person who scanned it.
  | 'feature_to_buy' // Closed ability to be bought for karma.
  | 'artifact' // Enchanted item.
  | 'event' // Event which affects the person who scanned it.
  | 'reagent' // Magical reagent
  | 'locus' // Ethic group locus
  | 'locus_charge' // Charge for the locus
  | 'box' // Empty box of some merchandise
  | 'body_storage'
  | 'spirit' // Not the spirit body! This is the spirit you can "enter"
  | 'spirit_jar'
  | 'drone' // Not the drone body! This is drone you can jack in
  | 'drone_mod'
  | 'sprite' // Sprite, can be used by technomancers
  | 'cyberdeck'
  | 'cyberdeck_mod'
  | 'software'
  | 'foundation_node'
  | 'reanimate_capsule'
  | 'ai_symbol'
  | 'focus' // Magic focus
  | 'focus_on_cooldown'
  | 'repair_kit'
  | 'armour'
  | 'weapon';

export const qrTypeList = [
  // Ones named in a CAPS_CASE are only generated by client Android app
  'HEALTHY_BODY'
  , 'WOUNDED_BODY'
  , 'CLINICALLY_DEAD_BODY'
  , 'ABSOLUTELY_DEAD_BODY'
  , 'ASTRAL_BODY'
  , 'ECTOPLASM_BODY'
  , 'ROBOT_BODY'
  // Ones in snake_case are rewritable ones stored in the database
  , 'empty' // Empty QR, can be written.
  , 'pill' // Pharmaceuticals and similar
  , 'implant' // Implant bought in the shop or cut from the body.
  , 'food' // Food item
  , 'ability' // Used for mental abilities - ability which affects the person who scanned it.
  , 'feature_to_buy' // Closed ability to be bought for karma.
  , 'artifact' // Enchanted item.
  , 'event' // Event which affects the person who scanned it.
  , 'reagent' // Magical reagent
  , 'locus' // Ethic group locus
  , 'locus_charge' // Charge for the locus
  , 'box' // Empty box of some merchandise
  , 'body_storage'
  , 'spirit' // Not the spirit body! This is the spirit you can "enter"
  , 'spirit_jar'
  , 'drone' // Not the drone body! This is drone you can jack in
  , 'drone_mod'
  , 'sprite' // Sprite, can be used by technomancers
  , 'cyberdeck'
  , 'cyberdeck_mod'
  , 'software'
  , 'foundation_node'
  , 'reanimate_capsule'
  , 'ai_symbol'
  , 'focus' // Magic focus
  , 'focus_on_cooldown'
  , 'repair_kit'
  , 'armour'
  , 'weapon'
] as const;
